version: "3.9"
services:
  customer:
    image: jackdavies606/customer-service:latest
    build: ./customer
    ports:
      - "8080:8080"
  item:
    image: jackdavies606/item-service:latest
    build: ./item
    ports:
      - "8081:8080"
  order:
    image: jackdavies606/order-service:latest
    build: ./order
    ports:
      - "8082:8080"
    environment:
      - ITEM_SERVICE_URL=http://172.17.0.1:8081