version: "3.9"
services:
  customer:
    image: customer-service:latest
    ports:
      - "8080:8080"
  item:
    image: item-service:latest
    ports:
      - "8081:8080"
  order:
    image: order-service:latest
    ports:
      - "8082:8080"